[package]
name = "ferrite"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "*"
rand = "*"
futures = "*"
env_logger = "*"
simple_logger = "*"
async-std = { version = "1.6.3", features = ["unstable", "attributes"] }
async-macros = "2.0.0"
futures-macro = "0.3.4"
