[package]
name = "ferrite"
version = "0.1.0"
authors = ["Soares Chen"]
edition = "2018"

[dependencies]
log = "*"
rand = "*"
futures = "*"
env_logger = "*"
simple_logger = "*"
async-std = { version = "1.5.0", features = ["unstable", "attributes"] }
async-macros = "2.0.0"
futures-macro = "0.3.4"
