[package]
name = "ferrite-session"
version = "0.1.0"
edition = "2018"
description = "Session Types DSL for Rust"
homepage = "https://github.com/maybevoid/ferrite"
repository = "https://github.com/maybevoid/ferrite"
authors = [ "Soares Chen <soares.chen@maybevoid.com>" ]
license = "MIT OR Apache-2.0"
keywords = [ "session-types" ]

[dependencies]
log = "0.4.11"
rand = "0.7.3"
paste = "1.0.1"
futures = "0.3.6"
lazy_static = "1.4.0"
env_logger = "0.7.1"
async-macros = "2.0.0"
ipc-channel = "0.14.1"
crossbeam-channel = "0.5.0"
tokio = { version = "1.2.0", features = [ "full" ] }
serde = { version = "1.0.123", features = [ "derive" ] }
